export default {
    // login: '/admin/admins/login',
    logout: '/admin/logout',
    register: '/admin/admin/send-otp',
    adminOtp: '/admin/admin/verify-otp',
    verifyOTP: '/auth/forgot-password',
    sendForgotOTP: '/admin/send-email/forgot-password/otp',
    changePassword: '/admin/change-password',
    forgot: '/auth/forgot-password',
    profile: '/user/user/profile',
    users: '/admin/users',
    brokers: '/admin/brokers',
    connectBroker: '/admin/brokers/connect',
    dhanConnect: '/admin/dhan/connect',
    profitSummary: '/user/user/profit-summary',
    strategy: '/admin/strategies',
    // strategy: '/admin/strategies/dashboard',
    pnlSummary: '/admin/positions/pnl-summary',
    checkBroker: '/admin/check-broker',
    userDashboard: '/admin/impersonate',
    positionSummary: '/admin/user/position/pnl-summary',
    manualReports: '/admin/reports/manual',
    algoReports: '/admin/reports/algo',
    downloadManualReport: '/admin/reports/manual/download',
    downloadAlgoReport: '/admin/reports/algo/download',
    deleteUserBroker: '/admin/user/delete_broker',
    createGroup: '/admin/strategies/create-group',
    orders: '/admin/fetch_orders',
    getJoiners: '/admin/users/search',
    assignGroup: '/admin/assing-group',
    groupMembers: '/admin/group-members',
    deleteBroker: '/admin/delete_broker',
    userLogin: '/user/user/login',
    referral: '/user/user/referral',
    orders: '/user/user/orders',
    positions: '/user/positions/user',
    pnlSummary: '/user/user/positions/pnl-summary',
    billingSummary: '/user/user/billing/summary',
    billingLedger: '/user/user/billing/ledger',
}
